CREATE TABLE players (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id uuid references auth.users,
  x decimal default random(),
  y decimal default random(),
  color int default floor(random() * 3)::int
);